# Makefile for github.com/zakame/k3s-prometheus-metrics

BINARY              := k3s-prometheus-metrics
CMD                 := ./cmd/$(BINARY)
BIN_DIR             := ./bin
CGO_ENABLED         ?= 0
RBAC_PATHS          := ./internal/controller/...
RBAC_OUT            := deploy/standard
ENVTEST_K8S_VERSION := 1.36.2
# ko is pinned by @version, not a go.mod tool directive: it (via its
# sigstore/cosign dependency) forces k8s.io/api,apimachinery,client-go
# ahead of what this controller otherwise needs, which the other dev tools
# don't.
KO_VERSION          := v0.19.1
DEV_PLATFORMS       := linux/amd64,linux/arm64
DEV_PLACEHOLDER     := CHANGE-ME/k3s-prometheus-metrics
DEV_LOCAL_KUSTOMIZATION := deploy/dev-local/kustomization.yaml
MARKDOWNLINT_CLI2_VERSION := 0.23.2
MERMAID_CLI_VERSION := 11.16.0

.DEFAULT_GOAL := help

.PHONY: help build test test-integration test-e2e cover lint vet fmt manifests docker-build run clean dev-image docs-lint

help: ## Show this help message
	@echo "Usage: make <target>"
	@echo ""
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2}'

build: ## Compile the binary to ./bin/k3s-prometheus-metrics
	@mkdir -p $(BIN_DIR)
	CGO_ENABLED=$(CGO_ENABLED) go build -o $(BIN_DIR)/$(BINARY) $(CMD)

test: ## Run all tests
	go test -v -count=1 ./...

test-integration: ## Run envtest-backed integration tests (test/integration/ and cmd/, build tag integration)
	KUBEBUILDER_ASSETS="$$(go run sigs.k8s.io/controller-runtime/tools/setup-envtest use $(ENVTEST_K8S_VERSION) -p path)" \
		go test -tags integration -v -count=1 ./test/integration/... $(CMD)/...

test-e2e: ## Run e2e tests (test/e2e/, build tag e2e); needs a real cluster with deploy/e2e already applied
	go test -tags e2e -v -timeout 20m ./test/e2e/...

cover: ## Run tests with coverage report
	go test -cover -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...
	go tool cover -func=coverage.txt

lint: ## Run golangci-lint if available, otherwise fall back to go vet
	@if command -v golangci-lint >/dev/null 2>&1; then \
		golangci-lint run; \
	else \
		echo "golangci-lint not found, falling back to go vet"; \
		go vet ./...; \
	fi

vet: ## Run go vet
	go vet ./...

fmt: ## Check formatting (exits non-zero if files need formatting)
	@test -z "$$(gofmt -l .)" || (gofmt -l . && exit 1)

docs-lint: ## Check docs formatting, spelling, and Mermaid diagram syntax
	go run github.com/golangci/misspell/cmd/misspell -error $$(git ls-files '*.md')
	@# markdownlint-cli2 has no inline flags to disable rules, so this
	@# writes a throwaway config instead of committing a dotfile.
	@# mermaid-cli extracts and renders every ```mermaid fence in a
	@# Markdown file itself when given one as -i; --no-sandbox works
	@# around Chromium's sandbox needing a privilege CI runners don't
	@# grant.
	@set -e; \
	tmp=$$(mktemp -d); \
	trap 'rm -rf "$$tmp"' EXIT; \
	printf '{"default": true, "MD013": false, "MD041": false, "MD060": false}' > "$$tmp/markdownlint.jsonc"; \
	echo '{"args": ["--no-sandbox"]}' > "$$tmp/puppeteer.json"; \
	npx -y markdownlint-cli2@$(MARKDOWNLINT_CLI2_VERSION) --config "$$tmp/markdownlint.jsonc" "**/*.md"; \
	for md in $$(git ls-files '*.md'); do \
		echo "Checking Mermaid diagrams in $$md"; \
		npx -y @mermaid-js/mermaid-cli@$(MERMAID_CLI_VERSION) -p "$$tmp/puppeteer.json" -i "$$md" -o "$$tmp/out.md"; \
	done

manifests: ## Generate deploy/standard/role.yaml from +kubebuilder:rbac markers
	go run sigs.k8s.io/controller-tools/cmd/controller-gen \
		rbac:roleName=$(BINARY) \
		paths="$(RBAC_PATHS)" \
		output:rbac:artifacts:config=$(RBAC_OUT)

docker-build: ## Build a local single-arch image only, no push (quick smoke test; use dev-image to test on a cluster)
	KO_DOCKER_REPO=$(BINARY) go run github.com/google/ko@$(KO_VERSION) build --local --bare --tags=dev $(CMD)

dev-image: ## Build+push a multiarch dev image via ko and generate an untracked overlay pointing at it (usage: make dev-image IMAGE=registry.example.com/k3s-prometheus-metrics TAG=dev)
	@test -n "$(IMAGE)" || (echo "Error: IMAGE is required, e.g. make dev-image IMAGE=registry.example.com/k3s-prometheus-metrics TAG=dev" >&2; exit 1)
	@test -n "$(TAG)" || (echo "Error: TAG is required, e.g. make dev-image IMAGE=registry.example.com/k3s-prometheus-metrics TAG=dev" >&2; exit 1)
	KO_DOCKER_REPO=$(IMAGE) go run github.com/google/ko@$(KO_VERSION) build --bare \
		--tags=$(TAG) --platform=$(DEV_PLATFORMS) $(CMD)
	@mkdir -p $(dir $(DEV_LOCAL_KUSTOMIZATION))
	@printf '%s\n' \
		'# Generated by `make dev-image`; gitignored, not tracked.' \
		'apiVersion: kustomize.config.k8s.io/v1beta1' \
		'kind: Kustomization' \
		'resources:' \
		'- ../dev' \
		'images:' \
		'- name: $(DEV_PLACEHOLDER)' \
		'  newName: $(IMAGE)' \
		'  newTag: $(TAG)' \
		> $(DEV_LOCAL_KUSTOMIZATION)
	@echo "Generated $(DEV_LOCAL_KUSTOMIZATION); deploy with: kubectl apply -k $(dir $(DEV_LOCAL_KUSTOMIZATION))"

run: build ## Build and run the controller against the current kubeconfig context
	$(BIN_DIR)/$(BINARY)

clean: ## Remove build artifacts (./bin/, coverage.txt)
	rm -rf $(BIN_DIR) coverage.txt
