apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- role-endpoints.yaml
- rolebinding-endpoints.yaml
- role-leader-election.yaml
- rolebinding-leader-election.yaml
- deployment.yaml
- control-plane-services.yaml
- servicemonitor.yaml
