name: Report

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test-results:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@d1b5dff021aa968b288b02285a8bf47471c5928a # v3.2.0
      with:
        artifact: test-results
        name: go test
        path: unit-tests.json
        reporter: golang-json
